apiVersion: v1
kind: Service
metadata:
  name: {{ include "auditlogger.fullname" . }}
  labels:
    {{- include "auditlogger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: 9900
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "auditlogger.selectorLabels" . | nindent 4 }}

